% Plot aggregated power for each configuration
figure;
hold on;

    year_idx = find(years == 2024); % find the index of year 2024
    plot(months_aggregated, total_power{1}(:, year_idx), '-o', ...
        'LineWidth', 1.5, 'MarkerSize', 6, 'Color', [0 0.4470 0.7410]); % custom color
    legend({'2024'}, 'Location', 'best');
    title(['Aggregated Power Generated by Month for 2024 with a ' char(configs(1).name)]);

xlabel('Month');
ylabel('Aggregated Power Generated (Watts)');
grid on;
hold off;

% Plot aggregated power for each configuration
figure;
hold on;

% If c == 1 (archimedes screw), only plot 2024
    year_idx = find(years == 2024); % find the index of year 2024
    plot(demand.VarName4 * 1000, '--s', 'LineWidth', 1.2, 'MarkerSize', 4, 'Color', [0.8500 0.3250 0.0980]);

    plot(months_aggregated, total_power{1}(:, year_idx), '-o', ...
        'LineWidth', 1.5, 'MarkerSize', 6, 'Color', [0 0.4470 0.7410]); % custom color
    legend({'Demand (in Watts)','Production 2024 (Archimedes)'}, 'Location', 'best');
    title(['Aggregated Power Generated by Month for 2024 with a ' char(configs(1).name)]);

xlabel('Month');
ylabel('Aggregated Power Generated (Watts)');
grid on;
hold off;

% Plot the difference (Demand - Production) for 2024 (Archimedes screw)
figure;
hold on;

% Index year 2024
year_idx = find(years == 2024);

% Find the prod 2024 (in Watts)
prod_2024 = total_power{1}(:, year_idx);

% Issue with the 1st value, so modify it
prod_2024(1) = 5.1885 * 10^4;

% Remove last value of prod_2024
prod_2024 = prod_2024(1:end-1);

% Convert kW to W (kWh → W)
demand_watts = demand.VarName4 * 1000;

% Compute difference (demand - production)
demand_minus_prod = demand_watts - prod_2024;

% Plot difference
plot(demand_minus_prod, '--s', 'LineWidth', 1.2, 'MarkerSize', 4, 'Color', [0.8500 0.3250 0.0980]);

% Legend and title
legend({'Demand - Production'}, 'Location', 'best');
title('Difference between Demand and Production 2024');
xlabel('Month');
ylabel('Difference (Watts)');
grid on;
hold off;

% Plot aggregated power for each configuration
figure;
hold on;

    year_idx = find(years == 2024); 
    plot(1:length(Thalf35.sum), Thalf35.sum*200*0.2, '-o', 'LineWidth', 2, 'Color', 'm');
    plot(demand.VarName4 * 1000, '--s', 'LineWidth', 1.2, 'MarkerSize', 4, 'Color', [0.8500 0.3250 0.0980]);
    plot(months_aggregated, total_power{1}(:, year_idx), '-o', ...
        'LineWidth', 1.5, 'MarkerSize', 6, 'Color', [0 0.4470 0.7410]);
    legend({'solar panel','Demand (in Watts)','Production 2024 (Archimedes)'}, 'Location', 'best');
    title(['Aggregated Power Generated by Hour for 2024 with a ' char(configs(1).name)]);

xlabel('Hour');
ylabel('Aggregated Power Generated (Watts)');
grid on;
hold off;

% Plot the difference (Demand - Production) for 2024 (Archimedes screw)
figure;
hold on;

year_idx = find(years == 2024);

% Size of the solar panel field
size_solar_panel = 200;

prod_2024 = total_power{1}(:, year_idx);

% Modify 1st value of prod_2024
prod_2024(1) = 5.1885 * 10^4;

% Remove last value of prod_2024
prod_2024 = prod_2024(1:end-1);

% kW to W
demand_watts = demand.VarName4 * 1000;

% Check if Thalf35 is a table and extract the needed column
if istable(Thalf35)
    Thalf35_data = Thalf35{:, 1};
else
    Thalf35_data = Thalf35;
end

% Shift values: first value takes the second value, etc.
Thalf35_data = Thalf35_data(2:end);  

% Thalf35_data = solar panel efficiency (0.2) * size (200 m²) * sunlight
Thalf35_data = Thalf35_data * size_solar_panel * 0.2;

% Add solar panel production to hydro production
prod_2024 = prod_2024 + Thalf35_data;

% Calculate the difference (demand - production)
demand_minus_prod = demand_watts - prod_2024;

% Plot the difference
plot(demand_minus_prod, '--s', 'LineWidth', 1.2, 'MarkerSize', 4, 'Color', [0.8500 0.3250 0.0980]);

legend({'Demand - Production'}, 'Location', 'best');
title('Difference between Demand and Production after installation');
xlabel('Hour');
ylabel('Difference (Watts)');
grid on;
hold off;

% Plot the difference (Demand - Production) after 25 years
figure;
hold on;

year_idx = find(years == 2024);

% Size of the solar panel field
size_solar_panel = 200;

prod_2024 = total_power{1}(:, year_idx);

% Modify 1st value of prod_2024
prod_2024(1) = 5.1885 * 10^4;

% Remove last value of prod_2024
prod_2024 = prod_2024(1:end-1);

% kW to W
demand_watts = demand.VarName4 * 1000;

% Extract sunlight data
if istable(Thalf35)
    Thalf35_data = Thalf35{:, 1};
else
    Thalf35_data = Thalf35;
end

% Shift values
Thalf35_data = Thalf35_data(2:end);  

% Account for solar panel degradation over 25 years
Thalf35_data = Thalf35_data * size_solar_panel * 0.2 * (0.95^25);

% Add to production
prod_2024 = prod_2024 + Thalf35_data;

% Calculate difference
demand_minus_prod = demand_watts - prod_2024;

% Plot
plot(demand_minus_prod, '--s', 'LineWidth', 1.2, 'MarkerSize', 4, 'Color', [0.8500 0.3250 0.0980]);

legend({'Demand - Production'}, 'Location', 'best');
title('Difference between Demand and Production after 25 years');
xlabel('Hour');
ylabel('Difference (Watts)');
grid on;
hold off;

% Plot aggregated power for each configuration (solar panel after 25 years)
figure;
hold on;

    year_idx = find(years == 2024); 
    plot(1:length(Thalf35.sum), Thalf35.sum*200*0.2*(0.95^25), '-o', 'LineWidth', 2, 'Color', 'm');
    plot(demand.VarName4 * 1000, '--s', 'LineWidth', 1.2, 'MarkerSize', 4, 'Color', [0.8500 0.3250 0.0980]);
    plot(months_aggregated, total_power{1}(:, year_idx), '-o', ...
        'LineWidth', 1.5, 'MarkerSize', 6, 'Color', [0 0.4470 0.7410]);
    legend({'solar panel after 25 years','Demand (in Watts)','Production 2024 (Archimedes)'}, 'Location', 'best');
    title(['Aggregated Power Generated by Hour for 2024 with a ' char(configs(1).name)]);

xlabel('Hour');
ylabel('Aggregated Power Generated (Watts)');
grid on;
hold off;

% Conversion: kW to W
power_30kW = power_30kW * 1000;
power_2x30kW = 2 * power_30kW;
power_3x30kW = 3 * power_30kW;

% Plot aggregated power for each configuration (hydro + PV + wind)
figure;
hold on;

year_idx = find(years == 2024); 

% Existing curves
plot(1:length(Thalf35.sum), Thalf35.sum*200*0.2, '-o', 'LineWidth', 2, 'Color', 'm');
plot(demand.VarName4 * 1000, '--s', 'LineWidth', 1.2, 'MarkerSize', 4, 'Color', [0.8500 0.3250 0.0980]);
plot(months_aggregated, total_power{1}(:, year_idx), '-o', ...
    'LineWidth', 1.5, 'MarkerSize', 6, 'Color', [0 0.4470 0.7410]);

% New curve: power_30kW
plot(power_3x30kW, '-d', 'LineWidth', 1.5, 'MarkerSize', 6, 'Color', [0.4940 0.1840 0.5560]);

% Updated legend
legend({'solar panel','Demand (in Watts)','Production 2024 (Archimedes)','30kW Power'}, 'Location', 'best');

title(['Aggregated Power Generated by Hour for 2024 with a ' char(configs(1).name)]);
xlabel('Hour');
ylabel('Aggregated Power Generated (Watts)');
grid on;
hold off;

% Plot difference (Demand - Production) for 2024 (Hydro + Solar + Wind)
figure;
hold on;

year_idx = find(years == 2024);

% Size of solar panel field
size_solar_panel = 50;

% Hydro production for 2024
prod_2024 = total_power{
